name: Unit Tests
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tests repository
        uses: actions/checkout@v2
        with:
          repository: feaser/microtbx-tests
          submodules: true
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: 'third_party'
      - name: Generate build environment
        working-directory: tests/base/LINUX_PC_GCC/build
        run: cmake ..
      - name: Build test application
        working-directory: tests/base/LINUX_PC_GCC/build
        run: make
      - name: Run test application
        working-directory: tests/base/LINUX_PC_GCC/build
        run: microtbx_tests
